name: Attest & Release

on:
  workflow_call:

permissions:
  contents: write
  attestations: write
  id-token: write

jobs:
  attest-and-release:
    # Remove the if on the job, handle it via the calling workflow
    runs-on: ubuntu-latest
    steps:
      - name: Get Version from Branch
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [[ $BRANCH_NAME == release/latest ]]; then
            RELEASE_VER=latest
          else
            RELEASE_VER=$(echo $BRANCH_NAME | sed 's/release\/v//')
          fi
          echo "RELEASE_VER=$RELEASE_VER" >> $GITHUB_ENV
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.ref_name }}
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      - name: Pack Package Artifacts
        run: bun pm pack
      - name: Attest Provenance
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: "*.tgz"
      - name: Download Attestation
        run: gh attestation download "*.tgz" --format json > sigstore-provenance-${{ env.RELEASE_VER }}.json
      - name: Create Tag
        run: |
          if [[ ${{ env.RELEASE_VER }} == latest ]]; then
            git tag latest --force
          else
            git tag v${{ env.RELEASE_VER }}
          fi
      - name: Create Release and Upload Assets
        run: |
          if [[ ${{ env.RELEASE_VER }} == latest ]]; then
            gh release create latest "*.tgz" sigstore-provenance-*.json \
              --title "Latest Release" \
              --notes 'Usage: `npm install github:${{ env.GITHUB_REPOSITORY }}#latest`'
          else
            gh release create v${{ env.RELEASE_VER }} "*.tgz" sigstore-provenance-*.json \
              --title "Release v${{ env.RELEASE_VER }}" \
              --notes 'Usage: `npm install github:${{ env.GITHUB_REPOSITORY }}#v${{ env.RELEASE_VER }}`'
          fi
      - name: Push Tag
        run: |
          if [[ ${{ env.RELEASE_VER }} == latest ]]; then
            git push origin latest --force
          else
            git push origin v${{ env.RELEASE_VER }}
          fi
      # - name: Enable Immutable Releases
      #   run: gh api repos/${{ env.GITHUB_REPOSITORY }}/immutable-releases --method PUT
